export const CITIES = [
  { value: 'albuquerque-nm', label: 'Albuquerque, NM' },
  { value: 'arlington-tx', label: 'Arlington, TX' },
  { value: 'atlanta-ga', label: 'Atlanta, GA' },
  { value: 'austin-tx', label: 'Austin, TX' },
  { value: 'baltimore-md', label: 'Baltimore, MD' },
  { value: 'boston-ma', label: 'Boston, MA' },
  { value: 'charlotte-nc', label: 'Charlotte, NC' },
  { value: 'chicago-il', label: 'Chicago, IL' },
  { value: 'cleveland-oh', label: 'Cleveland, OH' },
  { value: 'colorado-springs-co', label: 'Colorado Springs, CO' },
  { value: 'columbus-oh', label: 'Columbus, OH' },
  { value: 'dallas-tx', label: 'Dallas, TX' },
  { value: 'denver-co', label: 'Denver, CO' },
  { value: 'detroit-mi', label: 'Detroit, MI' },
  { value: 'fort-worth-tx', label: 'Fort Worth, TX' },
  { value: 'fresno-ca', label: 'Fresno, CA' },
  { value: 'honolulu-hi', label: 'Honolulu, HI' },
  { value: 'houston-tx', label: 'Houston, TX' },
  { value: 'indianapolis-in', label: 'Indianapolis, IN' },
  { value: 'jacksonville-fl', label: 'Jacksonville, FL' },
  { value: 'kansas-city-mo', label: 'Kansas City, MO' },
  { value: 'las-vegas-nv', label: 'Las Vegas, NV' },
  { value: 'long-beach-ca', label: 'Long Beach, CA' },
  { value: 'los-angeles-ca', label: 'Los Angeles, CA' },
  { value: 'louisville-ky', label: 'Louisville, KY' },
  { value: 'memphis-tn', label: 'Memphis, TN' },
  { value: 'miami-fl', label: 'Miami, FL' },
  { value: 'milwaukee-wi', label: 'Milwaukee, WI' },
  { value: 'minneapolis-mn', label: 'Minneapolis, MN' },
  { value: 'nashville-tn', label: 'Nashville, TN' },
  { value: 'new-orleans-la', label: 'New Orleans, LA' },
  { value: 'new-york-ny', label: 'New York, NY' },
  { value: 'oakland-ca', label: 'Oakland, CA' },
  { value: 'oklahoma-city-ok', label: 'Oklahoma City, OK' },
  { value: 'omaha-ne', label: 'Omaha, NE' },
  { value: 'philadelphia-pa', label: 'Philadelphia, PA' },
  { value: 'phoenix-az', label: 'Phoenix, AZ' },
  { value: 'portland-or', label: 'Portland, OR' },
  { value: 'raleigh-nc', label: 'Raleigh, NC' },
  { value: 'sacramento-ca', label: 'Sacramento, CA' },
  { value: 'san-antonio-tx', label: 'San Antonio, TX' },
  { value: 'san-diego-ca', label: 'San Diego, CA' },
  { value: 'san-francisco-ca', label: 'San Francisco, CA' },
  { value: 'seattle-wa', label: 'Seattle, WA' },
  { value: 'tampa-fl', label: 'Tampa, FL' },
  { value: 'tucson-az', label: 'Tucson, AZ' },
  { value: 'tulsa-ok', label: 'Tulsa, OK' },
  { value: 'virginia-beach-va', label: 'Virginia Beach, VA' },
  { value: 'washington-dc', label: 'Washington, D.C.' },
  { value: 'wichita-ks', label: 'Wichita, KS' },
];

export default CITIES;