export const INDUSTRIES = [
  { value: 'appliance-repair', label: 'Appliance Repair' },
  { value: 'cabinet-installation', label: 'Cabinet Installation' },
  { value: 'carpet-cleaning', label: 'Carpet Cleaning' },
  { value: 'cleaning-services', label: 'Cleaning Services' },
  { value: 'electrical-services', label: 'Electrical Services' },
  { value: 'flooring-installation', label: 'Flooring Installation' },
  { value: 'furniture-assembly', label: 'Furniture Assembly' },
  { value: 'furniture-delivery', label: 'Furniture Delivery Services' },
  { value: 'garage-door-repair', label: 'Garage Door Repair' },
  { value: 'gutter-cleaning', label: 'Gutter Cleaning' },
  { value: 'handyman-services', label: 'Handyman Services' },
  { value: 'hauling-dumping', label: 'Hauling / Dumping' },
  { value: 'hvac-installation', label: 'HVAC Installation & Repair' },
  { value: 'junk-removal', label: 'Junk Removal' },
  { value: 'lawn-care', label: 'Lawn Care' },
  { value: 'mobile-car-detailing', label: 'Mobile Car Detailing' },
  { value: 'moving-services', label: 'Moving Services' },
  { value: 'painting', label: 'Painting' },
  { value: 'pest-control', label: 'Pest Control' },
  { value: 'plumbing', label: 'Plumbing' },
  { value: 'pool-cleaning', label: 'Pool Cleaning' },
  { value: 'pressure-washing', label: 'Pressure Washing' },
  { value: 'roofing', label: 'Roofing' },
  { value: 'website-design', label: 'Website Design' },
  { value: 'window-cleaning', label: 'Window Cleaning' },
  { value: 'other', label: 'Other' },
];

export default INDUSTRIES;