export const PROGRAMS = [
  {
    id: 'pro',
    name: 'PRO',
    price: 497,
    priceDisplay: '$497',
    paymentType: 'flexible',
    paymentOptions: [
      {
        type: 'one-time',
        label: 'Pay in full',
        amount: 497,
        display: '$497',
        stripeLink: 'https://buy.stripe.com/cNibJ18by9Whbxqgee6c002',
      },
      {
        type: 'split',
        label: '2 payments',
        amount: 250,
        display: '2 × $250',
        totalAmount: 500,
        installments: 2,
        stripeLink: 'https://buy.stripe.com/28EdR977ufgBeJCd226c003',
      },
    ],
    features: [
      '4-hour Middleman Masterclass (core training)',
      'Step-by-step setup framework',
      'Marketing blueprint (how to attract customers)',
      'Business scripts and templates',
      'Pricing and deposit-collection strategy',
      'City-based launch guidance',
    ],
    description: 'DIY option — Everything you need to get started today',
    clarification: 'No website included • No coaching included',
    popular: false,
  },
  {
    id: 'elite',
    name: 'ELITE',
    price: 2500,
    priceDisplay: '$2,500',
    paymentType: 'flexible',
    paymentOptions: [
      {
        type: 'one-time',
        label: 'Pay in full',
        amount: 2500,
        display: '$2,500',
        stripeLink: 'https://buy.stripe.com/cNi5kD9fCc4p5920fg6c001',
      },
      {
        type: 'split',
        label: '2 payments',
        amount: 1250,
        display: '2 × $1,250',
        totalAmount: 2500,
        installments: 2,
        stripeLink: 'https://buy.stripe.com/14A8wPajGd8tdFy7HI6c004',
      },
    ],
    features: [
      'Fully built middleman business website',
      'Online booking and scheduling system',
      'Deposit collection setup',
      'Automated job dispatch system',
      'Service provider onboarding flow',
      'Branded business setup (business name & city)',
      'Business launch support',
      'Access to hosting, software, and automation systems',
    ],
    description: 'Done-For-You — Designed to operate in ~1 hour per week',
    popular: true,
  },
  {
    id: 'prime',
    name: 'PRIME',
    price: 10000,
    priceDisplay: '$10,000',
    paymentType: 'flexible',
    paymentOptions: [
      {
        type: 'one-time',
        label: 'Pay in full',
        amount: 10000,
        display: '$10,000',
        stripeLink: 'https://buy.stripe.com/9B64gzcrO0lH7ha0fg6c008',
      },
      {
        type: 'split',
        label: '2 payments',
        amount: 5000,
        display: '2 × $5,000',
        totalAmount: 10000,
        installments: 2,
        stripeLink: 'https://buy.stripe.com/28EcN577uc4p9pi1jk6c007',
      },
    ],
    features: [
      'Partnership with Shon-Jhon and his existing middleman businesses',
      'Licensed ownership position within an established middleman system',
      'Access to proven platform, infrastructure, and operations',
      'Centralized booking and dispatch system',
      'Access to active service provider network',
      'Brand and marketing leverage from existing businesses',
      'Priority scaling and expansion support',
      'Ongoing platform access and system management',
    ],
    description: 'Partner / License Model — Full partnership and licensing',
    popular: false,
  },
];

export default PROGRAMS;